In [4]:
import pandas as pd

filename = 'star-wars-survey_StarWars.csv'   # file needs to be in working directory
file = open(filename, 'r')

def getColumns(file):
    file.seek(0)
    columns = file.readline().strip().split(',')
        
    return columns


def buildLol(file):
    '''Build a list of lists representation of table.'''        
    lol = []
    for line in file:
        curRow = line.strip().split(',')
        lol.append(curRow)
        
    return lol

columns = getColumns(file)
StarWarsLol = buildLol(file)
five38df = pd.DataFrame(StarWarsLol)
five38df

,0,1,2,3,4,5,6,7,8,9,...,29,30,31,32,33,34,35,36,37,38
0,2,3292879998,Yes,Yes,Star Wars: Episode I The Phantom Menace,Star Wars: Episode II Attack of the Clones,Star Wars: Episode III Revenge of the Sith,Star Wars: Episode IV A New Hope,Star Wars: Episode V The Empire Strikes Back,Star Wars: Episode VI Return of the Jedi,...,Very favorably,I don't understand this question,Yes,No,No,Male,18-29,,High school degree,South Atlantic
1,3,3292879538,No,,,,,,,,...,,,,,Yes,Male,18-29,$0 - $24999,Bachelor degree,West South Central
2,4,3292765271,Yes,No,Star Wars: Episode I The Phantom Menace,Star Wars: Episode II Attack of the Clones,Star Wars: Episode III Revenge of the Sith,,,,...,Unfamiliar (N/A),I don't understand this question,No,,No,Male,18-29,$0 - $24999,High school degree,West North Central
3,5,3292763116,Yes,Yes,Star Wars: Episode I The Phantom Menace,Star Wars: Episode II Attack of the Clones,Star Wars: Episode III Revenge of the Sith,Star Wars: Episode IV A New Hope,Star Wars: Episode V The Empire Strikes Back,Star Wars: Episode VI Return of the Jedi,...,Very favorably,I don't understand this question,No,,Yes,Male,18-29,$100000 - $149999,Some college or Associate degree,West North Central
4,6,3292731220,Yes,Yes,Star Wars: Episode I The Phantom Menace,Star Wars: Episode II Attack of the Clones,Star Wars: Episode III Revenge of the Sith,Star Wars: Episode IV A New Hope,Star Wars: Episode V The Empire Strikes Back,Star Wars: Episode VI Return of the Jedi,...,Somewhat favorably,Greedo,Yes,No,No,Male,18-29,$100000 - $149999,Some college or Associate degree,West North Central
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
994,996,3288682656,Yes,Yes,Star Wars: Episode I The Phantom Menace,Star Wars: Episode II Attack of the Clones,Star Wars: Episode III Revenge of the Sith,Star Wars: Episode IV A New Hope,Star Wars: Episode V The Empire Strikes Back,Star Wars: Episode VI Return of the Jedi,...,Very favorably,Han,No,,Yes,Female,30-44,$50000 - $99999,Bachelor degree,New England
995,997,3288678886,Yes,No,,,,,Star Wars: Episode V The Empire Strikes Back,,...,Very favorably,I don't understand this question,No,,No,Female,18-29,$100000 - $149999,Some college or Associate degree,East North Central
996,998,3288675923,Yes,Yes,Star Wars: Episode I The Phantom Menace,Star Wars: Episode II Attack of the Clones,Star Wars: Episode III Revenge of the Sith,Star Wars: Episode IV A New Hope,Star Wars: Episode V The Empire Strikes Back,Star Wars: Episode VI Return of the Jedi,...,Very favorably,I don't understand this question,No,,Yes,Female,18-29,,Graduate degree,West South Central
997,999,3288672490,Yes,No,Star Wars: Episode I The Phantom Menace,,,Star Wars: Episode IV A New Hope,,Star Wars: Episode VI Return of the Jedi,...,Very favorably,Han,No,,No,Female,18-29,$50000 - $99999,Bachelor degree,Pacific
998,1000,3288672409,Yes,Yes,Star Wars: Episode I The Phantom Menace,Star Wars: Episode II Attack of the Clones,Star Wars: Episode III Revenge of the Sith,Star Wars: Episode IV A New Hope,Star Wars: Episode V The Empire Strikes Back,Star Wars: Episode VI Return of the Jedi,...,Very favorably,Han,No,,No,Female,18-29,,Some college or Associate degree,Pacific

In [15]:
five38df.columns = columns
five38dfv2 = five38df.set_index("rowid")

#Removing all un-needed columns
five38dfv3 = five38dfv2.drop(["RespondentID", "Which character shot first?","Are you familiar with the Expanded Universe?","Do you consider yourself to be a fan of the Expanded Universe?","Do you consider yourself to be a fan of the Star Trek franchise?","Gender", "Age","Household Income", "Education", "Location (Census Region)"], axis=1)

In [9]:
five38dfv3.columns.values.tolist()

['Have you seen any of the 6 films in the Star Wars franchise?',
 'Do you consider yourself to be a fan of the Star Wars film franchise?',
 'Have you ever seen Episode I?',
 'Have you ever seen Episode II?',
 'Have you ever seen Episode III?',
 'Have you ever seen Episode IV?',
 'Have you ever seen Episode V?',
 'Have you ever seen Episode VI?',
 'Please rank the Star Wars films in order of preference with 1 being your favorite film in the franchise and 6 being your least favorite film.',
 'Unnamed: 10',
 'Unnamed: 11',
 'Unnamed: 12',
 'Unnamed: 13',
 'Unnamed: 14',
 'Please state whether you view Han Solo favorably or unfavorably or are unfamiliar with him/her.',
 'Please state whether you view Luke Skywalker favorably or unfavorably or are unfamiliar with him/her.',
 'Please state whether you view Princess Leia Organa favorably or unfavorably or are unfamiliar with him/her.',
 'Please state whether you view Anakin Skywalker favorably or unfavorably or are unfamiliar with him/her.',
 'Please state whether you view Obiwan Kenobi favorably or unfavorably or are unfamiliar with him/her.',
 'Please state whether you view Emperor Palpatine favorably or unfavorably or are unfamiliar with him/her.',
 'Please state whether you view Darth Vader favorably or unfavorably or are unfamiliar with him/her.',
 'Please state whether you view Lando Calrissian favorably or unfavorably or are unfamiliar with him/her.',
 'Please state whether you view Boba Fett favorably or unfavorably or are unfamiliar with him/her.',
 'Please state whether you view C-3PO favorably or unfavorably or are unfamiliar with him/her.',
 'Please state whether you view R2 D2 favorably or unfavorably or are unfamiliar with him/her.',
 'Please state whether you view Jar Jar Binks favorably or unfavorably or are unfamiliar with him/her.',
 'Please state whether you view Padme Amidala favorably or unfavorably or are unfamiliar with him/her.',
 'Please state whether you view Yoda favorably or unfavorably or are unfamiliar with him/her.']

In [16]:
cleanedfive38df = five38dfv3[['Have you ever seen Episode IV?','Have you ever seen Episode V?','Have you ever seen Episode VI?','Please state whether you view Han Solo favorably or unfavorably or are unfamiliar with him/her.',
 'Please state whether you view Luke Skywalker favorably or unfavorably or are unfamiliar with him/her.',
 'Please state whether you view Princess Leia Organa favorably or unfavorably or are unfamiliar with him/her.',
 'Please state whether you view Anakin Skywalker favorably or unfavorably or are unfamiliar with him/her.',
 'Please state whether you view Obiwan Kenobi favorably or unfavorably or are unfamiliar with him/her.',
 'Please state whether you view Emperor Palpatine favorably or unfavorably or are unfamiliar with him/her.',
 'Please state whether you view Darth Vader favorably or unfavorably or are unfamiliar with him/her.',
 'Please state whether you view Lando Calrissian favorably or unfavorably or are unfamiliar with him/her.',
 'Please state whether you view Boba Fett favorably or unfavorably or are unfamiliar with him/her.',
 'Please state whether you view C-3PO favorably or unfavorably or are unfamiliar with him/her.',
 'Please state whether you view R2 D2 favorably or unfavorably or are unfamiliar with him/her.',
 'Please state whether you view Jar Jar Binks favorably or unfavorably or are unfamiliar with him/her.',
 'Please state whether you view Padme Amidala favorably or unfavorably or are unfamiliar with him/her.',
 'Please state whether you view Yoda favorably or unfavorably or are unfamiliar with him/her.']]

In [17]:
cleanedfive38df = cleanedfive38df.rename(columns={"Have you ever seen Episode IV?": "Episode IV", 
"Have you ever seen Episode V?": "Episode V", 
"Have you ever seen Episode VI?": "Episode VI",
'Please state whether you view Han Solo favorably or unfavorably or are unfamiliar with him/her.': 'Han Solo',
'Please state whether you view Luke Skywalker favorably or unfavorably or are unfamiliar with him/her.': "Luke Skywalker",
'Please state whether you view Princess Leia Organa favorably or unfavorably or are unfamiliar with him/her.': "Leia Organa",
'Please state whether you view Anakin Skywalker favorably or unfavorably or are unfamiliar with him/her.': "Anakin Skywalker",
'Please state whether you view Obiwan Kenobi favorably or unfavorably or are unfamiliar with him/her.': "Obiwan Kenobi",
'Please state whether you view Emperor Palpatine favorably or unfavorably or are unfamiliar with him/her.': "Emporer Palpatine",
'Please state whether you view Darth Vader favorably or unfavorably or are unfamiliar with him/her.': "Darth Vader", 
'Please state whether you view Lando Calrissian favorably or unfavorably or are unfamiliar with him/her.': "Lando Calrissian",
'Please state whether you view Boba Fett favorably or unfavorably or are unfamiliar with him/her.': "Boba Fett", 
'Please state whether you view C-3PO favorably or unfavorably or are unfamiliar with him/her.': "C-3PO",
'Please state whether you view R2 D2 favorably or unfavorably or are unfamiliar with him/her.': "R2 D2",
'Please state whether you view Jar Jar Binks favorably or unfavorably or are unfamiliar with him/her.': "Jar Jar Binks",
'Please state whether you view Padme Amidala favorably or unfavorably or are unfamiliar with him/her.': "Padme Amidala",
'Please state whether you view Yoda favorably or unfavorably or are unfamiliar with him/her.': "Yoda"
})

In [18]:
cleanedfive38df

,Episode IV,Episode V,Episode VI,Han Solo,Luke Skywalker,Leia Organa,Anakin Skywalker,Obiwan Kenobi,Emporer Palpatine,Darth Vader,Lando Calrissian,Boba Fett,C-3PO,R2 D2,Jar Jar Binks,Padme Amidala,Yoda
rowid,,,,,,,,,,,,,,,,,
2,Star Wars: Episode IV A New Hope,Star Wars: Episode V The Empire Strikes Back,Star Wars: Episode VI Return of the Jedi,Very favorably,Very favorably,Very favorably,Very favorably,Very favorably,Very favorably,Very favorably,Unfamiliar (N/A),Unfamiliar (N/A),Very favorably,Very favorably,Very favorably,Very favorably,Very favorably
3,,,,,,,,,,,,,,,,,
4,,,,Somewhat favorably,Somewhat favorably,Somewhat favorably,Somewhat favorably,Somewhat favorably,Unfamiliar (N/A),Unfamiliar (N/A),Unfamiliar (N/A),Unfamiliar (N/A),Unfamiliar (N/A),Unfamiliar (N/A),Unfamiliar (N/A),Unfamiliar (N/A),Unfamiliar (N/A)
5,Star Wars: Episode IV A New Hope,Star Wars: Episode V The Empire Strikes Back,Star Wars: Episode VI Return of the Jedi,Very favorably,Very favorably,Very favorably,Very favorably,Very favorably,Somewhat favorably,Very favorably,Somewhat favorably,Somewhat unfavorably,Very favorably,Very favorably,Very favorably,Very favorably,Very favorably
6,Star Wars: Episode IV A New Hope,Star Wars: Episode V The Empire Strikes Back,Star Wars: Episode VI Return of the Jedi,Very favorably,Somewhat favorably,Somewhat favorably,Somewhat unfavorably,Very favorably,Very unfavorably,Somewhat favorably,Neither favorably nor unfavorably (neutral),Very favorably,Somewhat favorably,Somewhat favorably,Very unfavorably,Somewhat favorably,Somewhat favorably
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
996,Star Wars: Episode IV A New Hope,Star Wars: Episode V The Empire Strikes Back,Star Wars: Episode VI Return of the Jedi,Somewhat favorably,Neither favorably nor unfavorably (neutral),Neither favorably nor unfavorably (neutral),Very favorably,Very favorably,Very favorably,Somewhat favorably,Somewhat favorably,Somewhat favorably,Somewhat unfavorably,Somewhat favorably,Very unfavorably,Very favorably,Very favorably
997,,Star Wars: Episode V The Empire Strikes Back,,Neither favorably nor unfavorably (neutral),Very favorably,Very favorably,Very favorably,Very favorably,Unfamiliar (N/A),Somewhat favorably,Unfamiliar (N/A),Unfamiliar (N/A),Neither favorably nor unfavorably (neutral),Very favorably,Somewhat favorably,Unfamiliar (N/A),Very favorably
998,Star Wars: Episode IV A New Hope,Star Wars: Episode V The Empire Strikes Back,Star Wars: Episode VI Return of the Jedi,Very favorably,Somewhat unfavorably,Very favorably,Very favorably,Very favorably,Unfamiliar (N/A),Very unfavorably,Unfamiliar (N/A),Very unfavorably,Very favorably,Very favorably,Very favorably,Very favorably,Very favorably
999,Star Wars: Episode IV A New Hope,,Star Wars: Episode VI Return of the Jedi,Very favorably,Very favorably,Very favorably,Very favorably,Very favorably,Unfamiliar (N/A),Very favorably,Unfamiliar (N/A),Somewhat unfavorably,Very favorably,Very favorably,Very unfavorably,Very favorably,Very favorably
1000,Star Wars: Episode IV A New Hope,Star Wars: Episode V The Empire Strikes Back,Star Wars: Episode VI Return of the Jedi,Very favorably,Somewhat favorably,Very favorably,Somewhat favorably,Very favorably,Very unfavorably,Somewhat unfavorably,Very favorably,Somewhat favorably,Very favorably,Very favorably,Very favorably,Very favorably,Very favorably

In [23]:
pd.unique(cleanedfive38df['Han Solo'].values)

,Episode IV,Episode V,Episode VI,Han Solo,Luke Skywalker,Leia Organa,Anakin Skywalker,Obiwan Kenobi,Emporer Palpatine,Darth Vader,Lando Calrissian,Boba Fett,C-3PO,R2 D2,Jar Jar Binks,Padme Amidala,Yoda
rowid,,,,,,,,,,,,,,,,,
2,Star Wars: Episode IV A New Hope,Star Wars: Episode V The Empire Strikes Back,Star Wars: Episode VI Return of the Jedi,2,2,2,2,2,2,2,0,0,2,2,2,2,2
3,,,,,,,,,,,,,,,,,
4,,,,1,1,1,1,1,0,0,0,0,0,0,0,0,0
5,Star Wars: Episode IV A New Hope,Star Wars: Episode V The Empire Strikes Back,Star Wars: Episode VI Return of the Jedi,2,2,2,2,2,1,2,1,1,2,2,2,2,2
6,Star Wars: Episode IV A New Hope,Star Wars: Episode V The Empire Strikes Back,Star Wars: Episode VI Return of the Jedi,2,1,1,1,2,2,1,0,2,1,1,2,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
996,Star Wars: Episode IV A New Hope,Star Wars: Episode V The Empire Strikes Back,Star Wars: Episode VI Return of the Jedi,1,0,0,2,2,2,1,1,1,1,1,2,2,2
997,,Star Wars: Episode V The Empire Strikes Back,,0,2,2,2,2,0,1,0,0,0,2,1,0,2
998,Star Wars: Episode IV A New Hope,Star Wars: Episode V The Empire Strikes Back,Star Wars: Episode VI Return of the Jedi,2,1,2,2,2,0,2,0,2,2,2,2,2,2
999,Star Wars: Episode IV A New Hope,,Star Wars: Episode VI Return of the Jedi,2,2,2,2,2,0,2,0,1,2,2,2,2,2
1000,Star Wars: Episode IV A New Hope,Star Wars: Episode V The Empire Strikes Back,Star Wars: Episode VI Return of the Jedi,2,1,2,1,2,2,1,2,1,2,2,2,2,2

In [28]:
cleanedfive38df = cleanedfive38df.replace(["Very favorably","Somewhat favorably","Neither favorably nor unfavorably (neutral)",
'Somewhat unfavorably', 'Unfamiliar (N/A)', 'Very unfavorably',''], [2,1,0,1,0,2,0])

In [29]:
pd.unique(cleanedfive38df['Han Solo'].values)

array([2, 0, 1])