In [1]:
import re
import pandas as pd
newHopePattern = r"(\b[A-Z ']+\b)\n[^\n]+[A-Z(]"
newHopeScript = open('Star-Wars-A-New-Hope.txt', 'r')
newHopeMatches = re.findall(newHopePattern, newHopeScript.read())

empireStrikesBackPattern = r"(\b[A-Z ']+\b)\n[^\n]+[A-Z(]"
empireStrikesBackScript = open('Star-Wars-The-Empire-Strikes-Back.txt','r')
empireStrikesBackMatches = re.findall(empireStrikesBackPattern, empireStrikesBackScript.read())

returnOfTheJediPattern = r"\n\n(\b[A-Z ']{3,}\b)\n"
returnOfTheJediScript = open('Star-Wars-Return-of-the-Jedi.txt','r')
returnOfTheJediMatches = re.findall(returnOfTheJediPattern, returnOfTheJediScript.read())

In [2]:
def createDictionary(matches):
    dic = {}
    for item in matches:
        if item in dic:
            dic[item] = [x+1 for x in dic[item]]
        else:
            dic[item] = [1]
    return dic

newHopeDic = createDictionary(newHopeMatches)
empireStrikesBackDic = createDictionary(empireStrikesBackMatches)
returnOfTheJediDic = createDictionary(returnOfTheJediMatches[:-1])

for item in empireStrikesBackDic:
    if item in newHopeMatches:
        newHopeDic[item] = [x+empireStrikesBackDic[item][0] for x in newHopeDic[item]]
    else:
        newHopeDic[item] = empireStrikesBackDic[item]

for item in returnOfTheJediDic:
    if item in newHopeMatches:
        newHopeDic[item] = [x+returnOfTheJediDic[item][0] for x in newHopeDic[item]]
    else:
        newHopeDic[item] = returnOfTheJediDic[item]

In [3]:
completeDic = dict(sorted(newHopeDic.items(), key=lambda x: x[1],reverse=True))

In [4]:
newHopeDic = createDictionary(newHopeMatches)
empireStrikesBackDic = createDictionary(empireStrikesBackMatches)
returnOfTheJediDic = createDictionary(returnOfTheJediMatches[:-1])

for key in completeDic:
    if key in newHopeDic:
        completeDic[key].append("Y")
    else:
        completeDic[key].append("N")

for key in completeDic:
    if key in empireStrikesBackDic:
        completeDic[key].append("Y")
    else:
        completeDic[key].append("N")

for key in completeDic:
    if key in returnOfTheJediDic:
        completeDic[key].append("Y")
    else:
        completeDic[key].append("N")

In [5]:
df = pd.DataFrame(completeDic)
df2 = df.transpose()
df2.columns = ["Number of lines", "In movie 4?", "In movie 5?", "In movie 6?"]
df2

                       Number of lines In movie 4? In movie 5? In movie 6?
LUKE                               476           Y           Y           Y
HAN                                433           Y           Y           Y
THREEPIO                           291           Y           Y           Y
LEIA                               224           Y           Y           Y
VADER                              132           Y           Y           Y
...                                ...         ...         ...         ...
RED THREE                            1           N           N           Y
NAVIGATOR                            1           N           N           Y
CONTROL ROOM COMMANDER               1           N           N           Y
SECOND COMMANDER                     1           N           N           Y
ANAKIN                               1           N           N           Y

[126 rows x 4 columns]